spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bus_app?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root          # 본인 MySQL 아이디
        password: park0724!    # 본인 MySQL 비밀번호
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            format_sql: true
        show-sql: true

custom:
    api:
        service-key: "0OhBU7ZCGIobDVKDeBJDpmDRqK3IRNF6jlf%2FJB2diFAf%2FfR2czYO9A4UTGcsOwppV6W2HVUeho%2FFPwXoL6DwqA%3D%3D"
        base-url: "http://ws.bus.go.kr/api/rest"